"""Offline checks for capture identity and corrupted input rejection."""
import hashlib
import json
import shutil
from pathlib import Path
import tempfile
import unittest
from unittest.mock import patch

from capture import MODULES, capture


class CaptureTests(unittest.TestCase):
    def capture_synthetic(self, spelling, mutate_file=False):
        name = 'ConformanceModule'
        source = f'__d({spelling},[],function(){{}});'.encode()
        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            bundles = root / 'bundles'
            bundles.mkdir()
            bundle = bundles / 'input.js'
            bundle.write_bytes(source)
            digest = hashlib.sha256(source).hexdigest()
            lock = dict(waVersion='fixture', bundleCount=1,
                        setHash=hashlib.sha256(f'{digest}:{len(source)}'.encode()).hexdigest(),
                        bundles=[dict(sha256=digest, size=len(source))])
            lock_path = root / 'lock.json'
            lock_path.write_text(json.dumps(lock))

            def ast(args, **kwargs):
                # An instrumented subprocess boundary, not a replacement AST
                # oracle: prove the verified bytes are sent without rereading.
                if mutate_file:
                    bundle.write_bytes(b'/* moved offsets */' + source)
                self.assertEqual(args[1], '-')
                self.assertEqual(kwargs.get('input'), source)
                return f'{name}\t0\t{len(source) - 1}\n'.encode()

            with patch('capture.MODULES', [name]), patch(
                'capture.subprocess.check_output', side_effect=ast
            ) as parser:
                capture(lock_path, bundles, root / 'output')
                parser.assert_called_once()
            self.assertEqual((root / 'output' / f'{name}.js').read_bytes(), source + b'\n')

    def test_ast_receives_the_verified_bytes_even_if_original_file_changes(self):
        self.capture_synthetic('"ConformanceModule"', mutate_file=True)

    def test_single_quoted_and_escaped_names_reach_the_ast(self):
        for spelling in ["'ConformanceModule'", r"'\u0043onformanceModule'"]:
            with self.subTest(spelling=spelling):
                self.capture_synthetic(spelling)

    def test_reviewed_provenance_bindings_are_pinned(self):
        # These complete-record pins are reviewed anchors, not regenerated by
        # capture.py. They include bundle identities/counts/offsets and, for
        # selected inputs, the source commit/path/full artifact hash. Updating
        # a capture requires reviewing these bindings before changing its pin.
        pins = {
            '2.3000.1045368834/provenance.json':
                '41e4e797af7ab73dc7b3cd1e63e033b264c4bd6aa0bc6f7157262064ed78c13a',
            '2.3000.1047483476/provenance.json':
                '30f9ee277d45596ca423bbb2e24b513ee2a7ca220d01bce0978255cd19d7ffe8',
        }
        for relative, expected in pins.items():
            with self.subTest(provenance=relative):
                raw = (Path(__file__).parent / relative).read_bytes()
                self.assertEqual(hashlib.sha256(raw).hexdigest(), expected)

    def test_committed_sources_match_every_recorded_span_hash(self):
        for version in ['2.3000.1045368834', '2.3000.1047483476']:
            root = Path(__file__).parent / version
            self.assert_source_set(root)

    def assert_source_set(self, root):
        self.assertEqual({p.name for p in root.glob("*.js")},
                         {name + ".js" for name in MODULES})
        evidence = json.loads((root / 'provenance.json').read_text())
        self.assertEqual({e['module'] for e in evidence['modules']}, set(MODULES))
        for entry in evidence['modules']:
            source = (root / (entry['module'] + '.js')).read_bytes()
            self.assertTrue(source.endswith(b';\n'))
            source = source[:-2]  # Capture's terminator, not part of the AST span.
            self.assertEqual(len(source), entry['end'] - entry['start'])
            self.assertEqual(hashlib.sha256(source).hexdigest(), entry['sourceSha256'])

    def test_unprovenanced_js_is_rejected(self):
        for version in ['2.3000.1045368834', '2.3000.1047483476']:
            with tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp) / 'snapshot'
                shutil.copytree(Path(__file__).parent / version, root)
                (root / 'WASmaxUnreviewed.js').write_text('__d("Unreviewed",[],function(){});')
                with self.assertRaises(AssertionError):
                    self.assert_source_set(root)

    def test_missing_modules_are_checked_across_the_complete_bundle_set(self):
        # Stub only the span subprocess: verify capture orchestration, not AST semantics.
        for missing in [False, True]:
            with self.subTest(missing=missing), tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp)
                bundles = root / 'bundles'
                bundles.mkdir()
                first = b'__d("Other",[],function(){});'
                second = b'__d("Wanted",[],function(){});'
                records = []
                for name, raw in [('a.js', first), ('b.js', second)]:
                    (bundles / name).write_bytes(raw)
                    records.append(dict(sha256=hashlib.sha256(raw).hexdigest(), size=len(raw)))
                fingerprint = hashlib.sha256('\n'.join(sorted(
                    f"{r['sha256']}:{r['size']}" for r in records)).encode()).hexdigest()
                lock = root / 'lock.json'
                lock.write_text(json.dumps(dict(waVersion='fixture', bundleCount=2,
                                                setHash=fingerprint, bundles=records)))
                def spans(args, **kwargs):
                    raw = kwargs['input']
                    return b'' if missing or raw == first else f'Wanted\t0\t{len(raw)-1}\n'.encode()
                with patch('capture.MODULES', ['Wanted']), patch(
                    'capture.subprocess.check_output', side_effect=spans
                ) as parser:
                    if missing:
                        with self.assertRaisesRegex(ValueError, 'missing modules'):
                            capture(lock, bundles, root / 'output')
                        self.assertFalse((root / 'output').exists())
                    else:
                        capture(lock, bundles, root / 'output')
                        self.assertTrue((root / 'output/Wanted.js').exists())
                    self.assertEqual(parser.call_count, 2)

    def test_changed_missing_extra_and_wrong_set_hash_are_rejected_before_ast(self):
        for failure in ['changed', 'missing', 'extra', 'setHash', 'count']:
            with self.subTest(failure=failure), tempfile.TemporaryDirectory() as tmp:
                root = Path(tmp)
                bundles = root / 'bundles'
                bundles.mkdir()
                source = b'fixture'
                digest = hashlib.sha256(source).hexdigest()
                lock = dict(waVersion='fixture', bundleCount=1,
                            setHash=hashlib.sha256(f'{digest}:7'.encode()).hexdigest(),
                            bundles=[dict(sha256=digest, size=7)])
                (bundles / 'input.js').write_bytes(source)
                if failure == 'changed':
                    (bundles / 'input.js').write_bytes(b'changed')
                elif failure == 'missing':
                    (bundles / 'input.js').unlink()
                elif failure == 'extra':
                    (bundles / 'extra.js').write_bytes(source)
                elif failure == 'setHash':
                    lock['setHash'] = '0' * 64
                else:
                    lock['bundleCount'] = 2
                lock_path = root / 'lock.json'
                lock_path.write_text(json.dumps(lock))
                with self.assertRaises(ValueError):
                    capture(lock_path, bundles, root / 'output')
                self.assertFalse((root / 'output').exists())


if __name__ == '__main__':
    unittest.main()
